export const cards = [
  {
    id: 1,
    title: "Mehandi/Tatoo Artists",
    desc: "Add art to your body",
    img: "./mehendi_tattoo/mehendi.webp",
  },
  {
    id: 2,
    title: "Makeup/Barber",
    desc: "Enhance your style",
    img: "./barber_makeup/makeup.webp",
  },
  {
    id: 3,
    title: "Photographers",
    desc: "Preserve your moments",
    img: "./photographers/photographer.jpeg",
  },
  {
    id: 4,
    title: "Automotive Mechanics",
    desc: "Aligning vehicle wheels",
    img: "./Mechanics/auto3.jpeg",
  },
  {
    id: 5,
    title: "Gardners",
    desc: "Beautify surroundings",
    img: "./gardners/gard6.webp",
  },
  {
    id: 6,
    title: "Plumber/Electricians",
    desc: "Comfort Matters",
    img: "./plumber_electrician/elect1.jpeg",
  },
  {
    id: 7,
    title: "Carpainters/Welders",
    desc: "Recast according to choice",
    img: "./welder_carpenter/car.webp",
  },
  {
    id: 8,
    title: "Event Planners",
    desc: "Color you dreams",
    img: "./EventPlanners/event.jpeg",
  },
  {
    id: 9,
    title: "Floral/Interior Designers",
    desc: "Color you dreams",
    img: "./Interior Designers/interior.jpeg",
  },
];

export const projects = [
  {
    id: 1,
    img: "./mehendi_tattoo/meh0.webp",
    pp: "./mehendi_tattoo/anshi.jpeg",
    cat: "Mehandi Designer",
    username: "Anshi Bose",
  },
  {
    id: 2,
    img: "./mehendi_tattoo/tat5.jpg",
    pp: "./mehendi_tattoo/cat.jpeg",
    cat: "Tatto Artist",
    username: "Ansh Baranwal",
  },
  {
    id: 3,
    img: "./barber_makeup/mak.webp",
    pp: "./barber_makeup/harshita.jpeg",
    cat: "Makeup Artist",
    username: "Harshita Mall",
  },
  {
    id: 4,
    img: "./EventPlanners/event_Plan.jpeg",
    pp: "./EventPlanners/profile-pic (3).png",
    cat: "Event Planner",
    username: "Ankush kumar",
  },
  {
    id: 5,
    img: "./photographers/photo.avif",
    pp: "./photographers/sagar.jpeg",
    cat: "Photographer",
    username: "Sagar Richards",
  },
  {
    id: 6,
    img: "./gardners/Gardeners.png",
    pp: "./gardners/prfl.avif",
    cat: "Gardeners",
    username: "Ramkesh Singh",
  },
  {
    id: 7,
    img: "./plumber_electrician/plumb.gif",
    pp: "./plumber_electrician/prfl.webp",
    cat: "Plumber",
    username: "Jaquii mandel",
  },
  {
    id: 8,
    img: "./Interior Designers/interior.jpeg",
    pp: "./Interior Designers/profile.webp",
    cat: "Interior Designer",
    username: "Vinnu Sharma",
  },
];

export const gigs = [
  {
    id: 1,
    img: "\./photographers/card.webp",
    pp: "\./photographers/photo2.jpeg",
    desc: "Transform your vision into photographs with me who exceeds expectations",
    price: 99,
    star: 5,
    username: "Ankush Kumar",
  },
  {
    id: 2,
    img: "./mehendi_tattoo/card.jpeg",
    pp: "./mehendi_tattoo/pf.webp",
    desc: "Crafting intricate and exquisite Mehendi designs with AI precision",
    price: 99,
    star: 5,
    username: "Ansh Baranwal",
  },
  {
    id: 3,
    img: "./EventPlanners/card.jpeg",
    pp: "./EventPlanners/pf.jpeg",
    desc: "I will plan an event very cheaply and effectively",
    price: 999,
    star: 5,
    username: "Harsh Kesharwani",
  },
  {
    id: 4,
    img: "./catering/card.jpeg",
    pp: "./catering/pf.webp",
    desc: "I will provide best catering service and food at any party",
    price: 999,
    star: 4,
    username: "Sagar Kumar",
  },
  {
    id: 5,
    img: "./barber_makeup/mak.webp",
    pp: "./barber_makeup/makeup.webp",
    desc: "I will recreate your dreams in high quality makeups",
    price: 199,
    star: 3,
    username: "AJ Jaiswal",
  },
  {
    id: 6,
    img: "./plumber_electrician/card.jpeg",
    pp: "./plumber_electrician/prfl.webp",
    desc: "I will fill your life with water without any leakage",
    price: 99,
    star: 4,
    username: "KK shrestha",
  },
  {
    id: 7,
    img: "./gardners/gard6.webp",
    pp: "./gardners/prfl.avif",
    desc: "I will beautify your life with flowers in your garden",
    price: 99,
    star: 5,
    username: "Sneha Singh",
  },
  {
    id: 8,
    img: "./Mechanics/auto3.jpeg",
    pp: "./Mechanics/prfl.jpeg",
    desc: "I will repair your wehicle and bring it back on track",
    price: 110,
    star: 4,
    username: "Akash Wailia",
  },
];
